version: "3" # versão do docker-compose
services: # serviços que precisamos colocar em conteiner
  # e um desses serviços é a nossa aplicação.
  app: # nome da nossa aplicação, pode ser qualquer nome, nesse caso vamos dar o nome de app
    build: 
      context: . # context é o diretório onde a gente está
    # command: "mix phx.server"
    # command: tail -f /dev/null
    tty: true
    ports:
      - '4000:4000'
    volumes:
        - '.:/var/www/html'
    working_dir: /var/www/html
    # network_mode: "host"
    networks:
        - main
  db:
    image: 'postgres:10'
    ports:
        - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
        PGPASSWORD: '${DB_PASSWORD:-hellop}'
        POSTGRES_DB: '${DB_DATABASE:-hellod}'
        POSTGRES_USER: '${DB_USERNAME:-hellou}'
        POSTGRES_PASSWORD: '${DB_PASSWORD:-hellop}'
    volumes:
        - 'main-pgsql:/var/lib/postgresql/data'
    networks:
        - main
    healthcheck:
        test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
        retries: 3
        timeout: 5s
networks:
    main:
        driver: bridge
volumes:
    main-pgsql:
        driver: local
